en:
  errors:
    user_exists?: "User not found"
    password_ok?: "Wrong Password"
    must_be_equal?: "Passwords are not matching"
    new_must_match?: "New Password are not matching"
    new_password_must_be_new?: "New password can't match the old one"
    unique_email?: "This email has been already used"
    email?: "Wrong format"
    not_blocked?: "You have been blocked mate"